source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'tryPod_Example', :exclusive => true do
  pod "tryPod", :path => "../"
end

target 'tryPod_Tests', :exclusive => true do
  pod "tryPod", :path => "../"

  
end
